# Generated by Django 5.2 on 2025-04-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_institute_party_poll_pollresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
