# Generated by Django 5.2 on 2025-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_alter_institute_id_alter_party_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='shortcut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
