# Generated by Django 5.2 on 2025-04-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0004_party_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='survey_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='surveyed_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
