# Generated by Django 5.2 on 2025-05-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0008_election_method_parliament_tasker_survey_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='election',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='method',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='parliament',
        ),
        migrations.RemoveField(
            model_name='result',
            name='party',
        ),
        migrations.RemoveField(
            model_name='result',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='tasker',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='Parliament',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='Tasker',
        ),
    ]
