# Generated by Django 5.2 on 2025-05-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0010_election_method_parliament_tasker_survey_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
