# Generated by Django 5.2 on 2025-05-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0011_alter_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='method',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parliament',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tasker',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
